# Welcome to Jekyll!
#

# Site settings
title: BioHackathon Europe
description: Barcelona 30 October - 3 November 2023
owner: Elixir Hub # or company name
first_published: 2023 # if migrating another site, the year of your first publish
email: webmaster@elixir-europe.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://biohackathon-europe.org" # the base hostname & protocol for your site
social:
  Twitter: https://twitter.com/hashtag/BioHackEU23
  GitHub: https://github.com/elixir-europe/biohackathon-europe-2023
  #linkedin-square: https://www.linkedin.com/company/9501702
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:biohackathon-europe@elixir-europe.org
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - scripts

# Build settings
markdown: kramdown
#sass:
#  style: compressed

collections:
  programmes:
    output: true
    permalink: /:collection/:path/
  landings:
    output: true
    permalink: /:collection/:path/
  committee:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
